@startuml

actor "Cliente" as U
participant " InterfacciaPartita" as B <<Boundary>>
participant " GestorePartita" as C <<Controller>>
participant "Partita" as E <<Entity>>   

U -> B : terminaPartita()
B -> C : terminaPartita(idPrenotazione, idCliente)
C -> C : verifica tempo trascorso

alt tempo > 90
    C -> E : getEsito("Sconfitta")
    E --> C : conferma
    
    C -> B : mostraRisultato("Sconfitta")
else tempo <= 90
    C -> E : getEsito("Vittoria")
    E --> C : conferma
    C -> B : mostraRisultato("Vittoria")
end

@enduml