@startuml
start

:Modifica;
:Elenca prenotazioni;
:Trova per id;
:Verifica tempo mancante;
if (mancano <24h?) then (si)
:Mostra errore: "modifica non eseguibile";
else (no)
:Inserisce dati;
:Modifica prenotazione;
:Trova stanza;
     if (stanza disponibile?) then (si)
     fork
     :Aggiorna stato nuova stanza ("occupata");
     fork again 
     :Aggiorma stato vecchia stanza ("libera");
     fork again
     :Modifica eseguita con successo;
     end fork
     else (no)
     :Mostra errore: "modifica non eseguibile";
     endif
endif
stop
@enduml