@startuml
start

:Scegli prenotazione;
:Invia prenotazione;
:Verifica tempo mancante;
if (mancano <24h?) then (si)
:Mostra errore: "modifica non eseguibile";
else (no)
:Inserisci dati prenotazione;
:Registra prenotazione;
:Trova stanza;
     if (stanza disponibile?) then (si)
     fork
     :Blocca nuova stanza;
     fork again 
     :Libera vecchia stanza;
     fork again
     :Modifica eseguita con successo;
     end fork
     else (no)
     :Mostra errore: "modifica non eseguibile";
     endif
endif
stop
@enduml