@startuml
start

:Inserisce credenziali;
:Registrazione;
:Verifica disponibilità;

if (email disponibile?) then (si)
fork
:Crea account;
fork again
:Mostra conferma;
end fork

else (no)
:Mostra errore: "e-mail già in uso";

endif
stop
@enduml