@startuml
start

:Termina partita;
:Richiedi fine;
:Get tempo trascorso;
:Stop cronometro;

if (tempo <= 90 min?) then (si)
   :Mostra risultato: "partita vinta";   
else (no)
:Mostra risultato: "partita persa";
endif

stop
@enduml