@startuml
start

:Accedi sezione prenotazione;
:Elenca tutte prenotazioni;
:Recupera prenotazioni;
if (ci sono prenotazioni?) then (si)
:Visualizza prenotazioni;
else (no)
:Mostra errore: "lista prenotazioni vuota";

endif
stop
@enduml
