@startuml
start

:Accedi sezione prenotazioni;
:Richiedi prenotazioni;
:Recupera dati prenotazioni;
if (ci sono prenotazioni?) then (si)
:Visualizza prenotazioni;

else (no)
:Mostra errore: "lista prenotazioni vuota";

endif
stop
@enduml
