@startuml
left to right direction

package "WebSite" {

    package "Area Catalogo e Prenotazioni" {
        usecase "Consulta Catalogo"
        usecase "Prenota Stanza" 
        usecase "Modifica Prenotazione" 
        usecase "Disdetta" 
        usecase "Registrazione" 
        usecase "Accesso"
        note right of "Consulta Catalogo" : Accessibile da:\n- Cliente\n- Amministratore
        note right of "Registrazione" : L'amministratore è già registrato
    }

    package "Area Amministrazione" {
        usecase "Aggiorna Catalogo Stanze"
        usecase "Visualizza Clienti Registrati"
        usecase "Visualizza Prenotazioni"
      
    }

    package "Area Gioco" {
        usecase "Avvia partita"
        usecase "Termina partita"
        usecase "Abbandona partita"
        usecase "Visualizza storico partite"
        usecase "Chiedi suggerimento"

    }

}    

@enduml