@startuml

actor Utente
participant "<<Boundary>>\nInterfacciaAccount" as B
participant "<<Controller>>\nGestoreAccount" as C
participant "<<Entity>>\nUtente" as E

Utente -> B : inserisciCredenziali(email, password)
B -> C : richiestaAccesso(email, password)
C -> C : verificaCredenziali(email, password)

alt Credenziali Corrette
  C->E : setStatoAccesso(eseguito)
  C-->B
  B-->Utente : accesso eseguito

else Credenziali Errate
  C->B : mostraErrore()
  B-->Utente : credenziali errate
end 

@enduml   