@startuml
actor Amministratore
participant "InterfacciaCatalogo" as B <<Boundary>>
participant "GestoreCatalogo" as C <<Controller>>
participant "Stanza" as E <<Entity>>

Amministratore -> B : accesso sezione catalogo 
B -> C : elencaStanze()
C -> C : trova stanze
C --> C : stanze
C --> B : mostra dati stanze
Amministratore -> B : inserisce idStanza, nome, tipo, descrizione

B -> C : aggiornaStanza(nome, tipo, descrizione)
C -> C : trovaPerId()
alt stanza non trovata
C --> C : errore
C --> B : "Errore: stanza '<idStanza>' non trovata" 
else stanza trovata
C --> C : stanza : Stanza
C -> E : setDatiStanze(nome, tipo, descrizione)
end
C --> B : conferma modifica catalogo
B --> Amministratore : modifica effettuata con successo
@enduml