@startuml

actor Cliente

participant "InterfacciaPartita" as B <<boundary>>
participant "GestorePartita" as C <<controller>>
participant "Partita" as E <<entity>>

Cliente -> B : avviaPartita()
activate B

B -> C : richiediAvvio()
activate C

C -> E : creaNuovaPartita()
activate E
E --> C : conferma creazione
deactivate E

C -> C : avviaCronometro()



C --> B : partita avviata
deactivate C

B --> Cliente : visualizza gioco e timer
deactivate B

@enduml