@startuml
actor Cliente

participant "InterfacciaPartita" as IP <<Boundary>>
participant "GestorePartita" as C <<Controller>>
participant "Partita" as P <<Entity>>

Cliente -> IP : chiede suggerimento

IP -> C : chiediSuggerimento(idPrenotazione, idStanza)
C -> P : getSuggerimenti()
alt suggerimentiRichiesti < 3

     P --> C : suggerimento

    C-->IP
    IP --> Cliente : mostraSuggerimento()
else limite raggiunto

    C -> IP : mostraErrore()
    IP --> Cliente : "Limite di suggerimenti raggiunto"

end
@enduml