@startuml

actor Utente
participant "Boundary:\nInterfacciaCatalogo" as B
participant "Controller:\nGestoreCatalogo" as C

Utente -> B : accesso sezione catalogo
B -> C : elencaStanze()
C -> C : trova stanze
C --> C : stanze
C --> B : mostra dati stanze
B --> Utente : visualizza catalogo
@enduml       