@startuml

actor Cliente
participant "<<Boundary>>\nInterfacciaPrenotazione" as B
participant "<<Controller>>\nGestorePrenotazione" as C
participant "<<Entity>>\nStanza" as E

Cliente -> B : inserisce dati
B -> C : prenota(idCliente, idStanza, giorno, ora)

activate C
C -> C : trovaStanza(idStanza)
C --> C : stanza 
C -> E : isDisponibile()
alt stanza LIBERA
    C -> E : setStato("occupata")
    C -> B : mostraConferma()
    B --> Cliente : confermata la prenotazione
else stanza OCCUPATA
    C -> B : mostraErrore()
    B --> Cliente : errore: stanza occupata
end
deactivate C

@enduml