@startuml

actor Cliente
participant "<<Boundary>>\nInterfacciaAccount" as B
participant "<<Controller>>\nGestoreAccount" as C
participant "<<Entity>>\nCliente" as E

Cliente -> B : inserisce credenziali(email, password)
B -> C : registrazione(email, password)


C -> C : verifica disponibilità(email)

alt Email Disponibile
    C -> E : <<create>> account(email, password)
    C -> B : mostraConferma()
    B --> Cliente : account creato con successo
else Email Già In Uso
    C -> B : mostraErrore("e-mail già in uso")
   
     B --> Cliente : registrazione fallita
end
        
@enduml  