@startuml

actor Cliente
participant "<<Boundary>>\nInterfacciaAccount" as B
participant "<<Controller>>\nGestoreAccount" as C
participant "<<Entity>>\nCliente" as E

Cliente -> B : inserisciCredenziali(email, password)
B -> C : registraNuovoUtente(email, password)

C -> C : verificaDisponibilità(email)

alt Email Disponibile
    C -> E : creaNuovoUtente(email, password)
    C -> B : mostraConferma()
    B --> Cliente : account creato con successo
else Email Già In Uso
    C -> B : mostraErrore("e-mail già in uso")
   
     B --> Cliente : registrazione fallita
end
        
@enduml  