@startuml

actor Amministratore
participant "<<Boundary>>\nInterfacciaPrenotazione" as B
participant "<<Controller>>\nGestorePrenotazione" as C

Amministratore -> B : accediSezionePrenotazioni()
B -> C : richiediPrenotazioni()

C -> C : recuperaDatiPrenotazioni(idPrenotazione)
C --> C : datiPrenotazioni

alt non ci sono prenotazioni
    C -> B : mostraErrore: ("lista prenotazioni vuota")
else prenotazioni presenti
    
    C-> B : mostraPrenotazioni()
    B --> Amministratore : visualizza prenotazioni

end
    
@enduml     