@startuml

actor Amministratore
participant "<<Boundary>>\nInterfacciaPrenotazione" as B
participant "<<Controller>>\nGestorePrenotazione" as C

Amministratore -> B : accedi sezione prenotazione
B -> C : elencaTuttePrenotazioni()
C -> C : recupera prenotazioni
C --> C : lista prenotazioni
alt non ci sono prenotazioni
    C -> B : mostraErrore: ("lista prenotazioni vuota")
    B --> Amministratore: lista vuota
else prenotazioni presenti
    C-> B : mostraPrenotazioni()
    B --> Amministratore : visualizza prenotazioni
end
    
@enduml     