@startuml
start

:Inserisce credenziali;
:Accesso;
:Trova per email e password;

if (credenziali corrette?) then (si)
fork
:Aggiorna stato accesso ("eseguito");
fork again
:Accesso eseguito;
end fork
else (no)
:Mostra errore: "credenziali errate";
endif
stop

@enduml